---
- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
    dpkg_options: 'force-confold,force-confdef'
    state: present

- name: Restart system
  shell: |
    shutdown -r now
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for port 22 to open
  connection: local
  become: false
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
