---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Be sure nginx enabled and started
  service:
    name: nginx
    enabled: yes
    state: started

- name: Copy nginx configuration
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx
