---
- name: Wait for port 22 to open
  connection: local
  wait_for:
    host: "{{ sacloud_ip_address }}"
    port: 22
    search_regex: OpenSSH
    delay: 10

- name: Provision sacloud resource
  remote_user: ubuntu
  become: yes
  become_method: sudo
  apt:
    name: apache2
    state: present
  run_once: true
  delegate_to: "{{ sacloud_ip_address }}"
